"""weekmenu servings

Revision ID: 11562a5d1545
Revises: 81b07145275e
Create Date: 2026-07-20 11:24:07.764445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # custom types (MoneyCents, PreciseDecimal) in autogenerate


# revision identifiers, used by Alembic.
revision: str = '11562a5d1545'
down_revision: Union[str, Sequence[str], None] = '81b07145275e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Spurious accounts.type modify_type verwijderd (bewuste VARCHAR-drift, zie CLAUDE.md).
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))

    with op.batch_alter_table('week_plan_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_plan_entries', schema=None) as batch_op:
        batch_op.drop_column('servings')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('servings')

    # ### end Alembic commands ###
