"""shopping list quantity

Revision ID: 1a1c3b781746
Revises: 11562a5d1545
Create Date: 2026-07-20 13:08:46.597747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # custom types (MoneyCents, PreciseDecimal) in autogenerate


# revision identifiers, used by Alembic.
revision: str = '1a1c3b781746'
down_revision: Union[str, Sequence[str], None] = '11562a5d1545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Spurious accounts.type modify_type verwijderd (bewuste VARCHAR-drift, zie CLAUDE.md).
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
