"""ingredient in stock

Revision ID: 5d1c31929dab
Revises: 1a1c3b781746
Create Date: 2026-07-20 18:33:13.509110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # custom types (MoneyCents, PreciseDecimal) in autogenerate


# revision identifiers, used by Alembic.
revision: str = '5d1c31929dab'
down_revision: Union[str, Sequence[str], None] = '1a1c3b781746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Spurious accounts.type modify_type verwijderd (bewuste VARCHAR-drift, zie CLAUDE.md).
    # server_default zodat bestaande ingrediënt-rijen True krijgen (autogenerate zet dit niet).
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('in_stock', sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###
