"""weekmenu schema

Tien nieuwe tabellen voor de Weekmenu-feature (recepten, weekplanning,
boodschappenlijst) — puur additief, raakt geen Financiën-tabel. De spurious
alter_column op accounts.type die autogenerate meegaf (bewust geaccepteerde
enum-VARCHAR-drift, zie docstring d8b3f0a7c1e2) is handmatig verwijderd.

Revision ID: 81b07145275e
Revises: b3f7d1a9c4e2
Create Date: 2026-07-20 00:04:42.626555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # custom types (MoneyCents, PreciseDecimal) in autogenerate


# revision identifiers, used by Alembic.
revision: str = '81b07145275e'
down_revision: Union[str, Sequence[str], None] = 'b3f7d1a9c4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_recipe_categories_name'))
    )
    op.create_table('recipe_difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_difficulties')),
    sa.UniqueConstraint('name', name=op.f('uq_recipe_difficulties_name'))
    )
    op.create_table('recipe_moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_moments')),
    sa.UniqueConstraint('name', name=op.f('uq_recipe_moments_name'))
    )
    op.create_table('recipe_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_times')),
    sa.UniqueConstraint('name', name=op.f('uq_recipe_times_name'))
    )
    op.create_table('shopping_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_shopping_categories_name'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('pantry_type', sa.Enum('always_home', 'pantry', 'normal', name='pantry_type', native_enum=False), nullable=False),
    sa.Column('shopping_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shopping_category_id'], ['shopping_categories.id'], name=op.f('fk_ingredients_shopping_category_id_shopping_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_ingredients_normalized_name'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('moment_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['recipe_categories.id'], name=op.f('fk_recipes_category_id_recipe_categories')),
    sa.ForeignKeyConstraint(['difficulty_id'], ['recipe_difficulties.id'], name=op.f('fk_recipes_difficulty_id_recipe_difficulties')),
    sa.ForeignKeyConstraint(['moment_id'], ['recipe_moments.id'], name=op.f('fk_recipes_moment_id_recipe_moments')),
    sa.ForeignKeyConstraint(['time_id'], ['recipe_times.id'], name=op.f('fk_recipes_time_id_recipe_times')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('manually_added', sa.Boolean(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['shopping_categories.id'], name=op.f('fk_shopping_list_items_category_id_shopping_categories')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_shopping_list_items_ingredient_id_ingredients')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_shopping_list_items_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items'))
    )
    op.create_table('week_plan_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.String(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_week_plan_entries_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_week_plan_entries')),
    sa.UniqueConstraint('date', name=op.f('uq_week_plan_entries_date'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('week_plan_entries')
    op.drop_table('shopping_list_items')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    op.drop_table('ingredients')
    op.drop_table('shopping_categories')
    op.drop_table('recipe_times')
    op.drop_table('recipe_moments')
    op.drop_table('recipe_difficulties')
    op.drop_table('recipe_categories')
    # ### end Alembic commands ###
