"""recipe categories many to many

Revision ID: 835d05468274
Revises: 5d1c31929dab
Create Date: 2026-07-20 18:53:54.652801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types  # custom types (MoneyCents, PreciseDecimal) in autogenerate


# revision identifiers, used by Alembic.
revision: str = '835d05468274'
down_revision: Union[str, Sequence[str], None] = '5d1c31929dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Spurious accounts.type modify_type verwijderd (bewuste VARCHAR-drift, zie CLAUDE.md).
    op.create_table('recipe_category_links',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['recipe_categories.id'], name=op.f('fk_recipe_category_links_category_id_recipe_categories')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_category_links_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id', name=op.f('pk_recipe_category_links'))
    )

    # Bestaande category_id per recept overzetten naar de nieuwe koppeltabel vóórdat
    # de kolom verdwijnt (each recept had hooguit één categorie, dus geen dedupe nodig).
    op.execute(
        "INSERT INTO recipe_category_links (recipe_id, category_id) "
        "SELECT id, category_id FROM recipes WHERE category_id IS NOT NULL"
    )

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_category_id_recipe_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipes_category_id_recipe_categories'), 'recipe_categories', ['category_id'], ['id'])

    # Eén categorie per recept terugzetten (eerste koppeling op category_id wint —
    # data-verlies bij recepten met >1 categorie is inherent aan deze downgrade).
    op.execute(
        "UPDATE recipes SET category_id = ("
        "SELECT MIN(category_id) FROM recipe_category_links "
        "WHERE recipe_category_links.recipe_id = recipes.id"
        ")"
    )

    op.drop_table('recipe_category_links')
    # ### end Alembic commands ###
