"""initieel schema

Revision ID: defd059dcd0f
Revises: 
Create Date: 2026-07-05 13:26:11.372116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.types


# revision identifiers, used by Alembic.
revision: str = 'defd059dcd0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contexts')),
    sa.UniqueConstraint('name', name=op.f('uq_contexts_name'))
    )
    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('bank', sa.Enum('KBC', 'Fortis', 'Andere', name='bank', native_enum=False), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imports'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('bank', sa.Enum('KBC', 'Fortis', 'Andere', name='bank', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('zicht', 'spaar', 'belegging', 'andere', name='account_type', native_enum=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_accounts_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('context_id', 'name', name=op.f('uq_accounts_context_id_name'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Inkomen', 'Uitgaven', 'Sparen', name='category_type', native_enum=False), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_categories_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('context_id', 'type', 'name', name=op.f('uq_categories_context_id_type_name'))
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('principal', app.types.MoneyCents(), nullable=False),
    sa.Column('annual_rate', app.types.PreciseDecimal(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('monthly_payment', app.types.MoneyCents(), nullable=False),
    sa.Column('property_value_paid', app.types.MoneyCents(), nullable=True),
    sa.Column('property_value_estimate', app.types.MoneyCents(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_loans_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('asset_class', sa.Enum('contant', 'etf_fondsen', 'pensioensparen', 'groepsverzekering', 'woning', 'aandelen', name='asset_class', native_enum=False), nullable=False),
    sa.Column('value', app.types.MoneyCents(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_net_worth_snapshots_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_net_worth_snapshots')),
    sa.UniqueConstraint('context_id', 'snapshot_date', 'asset_class', name=op.f('uq_net_worth_snapshots_context_id_snapshot_date_asset_class'))
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('owner_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_context_id'], ['contexts.id'], name=op.f('fk_securities_owner_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities'))
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', app.types.MoneyCents(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_snapshots_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_snapshots')),
    sa.UniqueConstraint('account_id', 'snapshot_date', name=op.f('uq_account_snapshots_account_id_snapshot_date'))
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', app.types.MoneyCents(), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name=op.f('ck_budgets_month_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budgets_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('category_id', 'year', 'month', name=op.f('uq_budgets_category_id_year_month'))
    )
    op.create_table('categorization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match_field', sa.Enum('counterparty_name', 'counterparty_iban', 'description', name='match_field', native_enum=False), nullable=False),
    sa.Column('match_type', sa.Enum('contains', 'equals', 'regex', name='match_type', native_enum=False), nullable=False),
    sa.Column('match_value', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_from_correction', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_categorization_rules_category_id_categories')),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_categorization_rules_context_id_contexts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorization_rules'))
    )
    op.create_table('loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', app.types.MoneyCents(), nullable=False),
    sa.Column('interest_part', app.types.MoneyCents(), nullable=False),
    sa.Column('principal_part', app.types.MoneyCents(), nullable=False),
    sa.Column('balance_after', app.types.MoneyCents(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_payments_loan_id_loans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_payments'))
    )
    op.create_table('security_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', app.types.PreciseDecimal(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_security_prices_security_id_securities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_prices')),
    sa.UniqueConstraint('security_id', 'date', name=op.f('uq_security_prices_security_id_date'))
    )
    op.create_table('security_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='security_side', native_enum=False), nullable=False),
    sa.Column('shares', app.types.PreciseDecimal(), nullable=False),
    sa.Column('price_per_share', app.types.PreciseDecimal(), nullable=False),
    sa.Column('fee', app.types.MoneyCents(), nullable=False),
    sa.Column('tax', app.types.MoneyCents(), nullable=False),
    sa.Column('total', app.types.MoneyCents(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_security_transactions_security_id_securities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_transactions'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', app.types.MoneyCents(), nullable=False),
    sa.Column('type', sa.Enum('Inkomen', 'Uitgaven', 'Sparen', name='category_type', native_enum=False), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=True),
    sa.Column('counterparty_iban', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'import_kbc', 'import_fortis', name='transaction_source', native_enum=False), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('import_hash', sa.String(), nullable=True),
    sa.Column('categorization', sa.Enum('auto', 'manual', 'uncategorized', name='categorization', native_enum=False), nullable=False),
    sa.Column('is_internal_transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories')),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], name=op.f('fk_transactions_context_id_contexts')),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], name=op.f('fk_transactions_import_id_imports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('import_hash', name=op.f('uq_transactions_import_hash'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_context_id'), ['context_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_context_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    op.drop_table('security_transactions')
    op.drop_table('security_prices')
    op.drop_table('loan_payments')
    op.drop_table('categorization_rules')
    op.drop_table('budgets')
    op.drop_table('account_snapshots')
    op.drop_table('securities')
    op.drop_table('net_worth_snapshots')
    op.drop_table('loans')
    op.drop_table('categories')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('imports')
    op.drop_table('contexts')
    # ### end Alembic commands ###
